### ISSUE TITLE
importing two templates

### ISSUE THREAD

**Issue by nexus-os-fs** [soulruins/zabbix#1]
when importing the second Open Hardware Monitor.yaml template, zabbix suggests rewriting LibreHardwareMonitor.yaml, is it possible to somehow import both of them?

**Comment by soulruins** [comment]
Change main uuid

1. Open `OpenHardwareMonitor.yaml`
2. Find `uuid: 755251f224984459a760e9a00dcda921` (line 10)
3. Replace uuid (example: `755251f224984459a760e9a00dcda922`)
4. Save and import

It should work )

**Comment by nexus-os-fs** [comment]
I tried, but it gives an error
```
Import failed
Invalid parameter "/1": item with the same UUID already exists.
```
![img-2024-06-14-10-30-20](https://github.com/soulruins/zabbix/assets/163771778/43f92833-a7f6-4d74-9a60-676113a0cb06)

for the test, I tried to change all the uids, but it still didn't work

**Comment by soulruins** [comment]
> for the test, I tried to change all the uids, but it still didn't work

It's working. Regenerated all uuids and successfully imported template

Powershell script:
```powershell
cat OpenHardwareMonitor.yaml | % {$_ -replace "uuid\:\s[a-z0-9]{32}", "uuid: $((New-Guid).ToString() -replace '-')"} | Out-File .\OpenHardwareMonitor_newuuid.yaml
```
Attached new version (after script, import and export, zabbix v7.0) and old (after script, zabbix v6.2) temlpates
[tpl.zip](https://github.com/user-attachments/files/15834945/tpl.zip)

**Comment by nexus-os-fs** [comment]
thank you! it works :)
